# Generated by Django 3.0.6 on 2020-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
